namespace LearnKit.Domain.Roadmaps;

/// <summary>
/// Represents one ordered step inside a learning zone.
/// </summary>
public sealed class LearningStep
{
    /// <summary>
    /// Creates a new learning step.
    /// </summary>
    public LearningStep(
        string key,
        string title,
        string? summary,
        int sortOrder)
    {
        ValidateRequired(key, nameof(key), "Step key is required.");
        ValidateRequired(title, nameof(title), "Step title is required.");
        ValidateSortOrder(sortOrder);

        Key = key.Trim();
        Title = title.Trim();
        Summary = NormalizeOptional(summary);
        SortOrder = sortOrder;
    }

    /// <summary>
    /// Unique step identifier.
    /// Generated by persistence layer.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Stable key used to identify the step.
    /// </summary>
    public string Key { get; private set; }

    /// <summary>
    /// Step title shown to the user.
    /// </summary>
    public string Title { get; private set; }

    /// <summary>
    /// Short step description.
    /// </summary>
    public string Summary { get; private set; }

    /// <summary>
    /// Determines the position inside the zone.
    /// </summary>
    public int SortOrder { get; private set; }

    /// <summary>
    /// Renames the step.
    /// </summary>
    public void Rename(string title)
    {
        ValidateRequired(title, nameof(title), "Step title is required.");

        Title = title.Trim();
    }

    /// <summary>
    /// Updates the step summary.
    /// </summary>
    public void UpdateSummary(string? summary)
    {
        Summary = NormalizeOptional(summary);
    }

    /// <summary>
    /// Moves the step to a new position.
    /// </summary>
    public void MoveTo(int sortOrder)
    {
        ValidateSortOrder(sortOrder);

        SortOrder = sortOrder;
    }

    private static void ValidateRequired(
        string? value,
        string parameterName,
        string message)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException(message, parameterName);
        }
    }

    private static void ValidateSortOrder(int sortOrder)
    {
        if (sortOrder < 1)
        {
            throw new ArgumentOutOfRangeException(
                nameof(sortOrder),
                "Sort order must be greater than zero.");
        }
    }

    private static string NormalizeOptional(string? value)
    {
        return value?.Trim() ?? string.Empty;
    }
}
