namespace LearnKit.Domain.Articles;

/// <summary>
/// Represents one article in a learning step.
///
/// An article owns its blocks and controls its publishing state.
/// </summary>
public sealed class Article
{
    private readonly List<ArticleBlock> _blocks = [];

    /// <summary>
    /// Creates a new draft article.
    /// </summary>
    public Article(
        string slug,
        string title,
        string? summary = null)
    {
        ValidateRequired(slug, nameof(slug), "Article slug is required.");
        ValidateRequired(title, nameof(title), "Article title is required.");

        Slug = slug.Trim();
        Title = title.Trim();
        Summary = NormalizeOptional(summary);
        Status = ArticleStatus.Draft;
    }

    /// <summary>
    /// Unique article identifier.
    /// Generated by persistence layer.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// URL-friendly article identifier.
    /// </summary>
    public string Slug { get; private set; }

    /// <summary>
    /// Article title shown to the user.
    /// </summary>
    public string Title { get; private set; }

    /// <summary>
    /// Short article description.
    /// </summary>
    public string Summary { get; private set; }

    /// <summary>
    /// Current article publishing state.
    /// </summary>
    public ArticleStatus Status { get; private set; }

    /// <summary>
    /// Ordered article blocks.
    /// </summary>
    public IReadOnlyCollection<ArticleBlock> Blocks =>
        _blocks.OrderBy(block => block.SortOrder).ToList();

    /// <summary>
    /// Indicates whether the article is published.
    /// </summary>
    public bool IsPublished => Status == ArticleStatus.Published;

    /// <summary>
    /// Renames the article.
    /// </summary>
    public void Rename(string title)
    {
        ValidateRequired(title, nameof(title), "Article title is required.");

        Title = title.Trim();
    }

    /// <summary>
    /// Updates the article summary.
    /// </summary>
    public void UpdateSummary(string? summary)
    {
        Summary = NormalizeOptional(summary);
    }

    /// <summary>
    /// Publishes the article.
    /// </summary>
    public void Publish()
    {
        Status = ArticleStatus.Published;
    }

    /// <summary>
    /// Moves the article back to draft.
    /// </summary>
    public void MoveToDraft()
    {
        Status = ArticleStatus.Draft;
    }

    /// <summary>
    /// Archives the article.
    /// </summary>
    public void Archive()
    {
        Status = ArticleStatus.Archived;
    }

    /// <summary>
    /// Adds a new block to the article.
    /// </summary>
    public void AddBlock(ArticleBlock block)
    {
        ArgumentNullException.ThrowIfNull(block);

        _blocks.Add(block);
        ReorderBlocks();
    }

    private void ReorderBlocks()
    {
        var sortOrder = 1;

        foreach (var block in _blocks.OrderBy(block => block.SortOrder))
        {
            block.MoveTo(sortOrder++);
        }
    }

    private static void ValidateRequired(
        string? value,
        string parameterName,
        string message)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException(message, parameterName);
        }
    }

    private static string NormalizeOptional(string? value)
    {
        return value?.Trim() ?? string.Empty;
    }
}