//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend55.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend55.Portal.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        
        
        
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt według kategorii.
        /// </summary>
        public static string Subscriptions_Categories_Title {
            get {
                return ResourceManager.GetString("Subscriptions.Categories.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narzędzia AI.
        /// </summary>
        public static string Subscriptions_Category_AI {
            get {
                return ResourceManager.GetString("Subscriptions.Category.AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edukacja.
        /// </summary>
        public static string Subscriptions_Category_Education {
            get {
                return ResourceManager.GetString("Subscriptions.Category.Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprogramowanie.
        /// </summary>
        public static string Subscriptions_Category_Software {
            get {
                return ResourceManager.GetString("Subscriptions.Category.Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        public static string Subscriptions_Category_Streaming {
            get {
                return ResourceManager.GetString("Subscriptions.Category.Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj subskrypcję.
        /// </summary>
        public static string Subscriptions_Create_Actions_Create {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Actions.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie....
        /// </summary>
        public static string Subscriptions_Create_Actions_Creating {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Actions.Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź podstawowe dane usługi. Po zapisaniu subskrypcja od razu pojawi się na liście..
        /// </summary>
        public static string Subscriptions_Create_Dialog_Description {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Dialog.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj subskrypcję.
        /// </summary>
        public static string Subscriptions_Create_Dialog_Title {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Dialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się dodać subskrypcji. Spróbuj ponownie..
        /// </summary>
        public static string Subscriptions_Create_Error {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        public static string Subscriptions_Create_Fields_Amount {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Fields.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Subscriptions_Create_Fields_Category {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Fields.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waluta.
        /// </summary>
        public static string Subscriptions_Create_Fields_Currency {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Fields.Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa usługi.
        /// </summary>
        public static string Subscriptions_Create_Fields_Name {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Fields.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to np. Streaming.
        /// </summary>
        public static string Subscriptions_Create_Placeholders_Category {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Placeholders.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to np. Netflix.
        /// </summary>
        public static string Subscriptions_Create_Placeholders_Name {
            get {
                return ResourceManager.GetString("Subscriptions.Create.Placeholders.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 sierpnia.
        /// </summary>
        public static string Subscriptions_Date_August2 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.August2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 sierpnia.
        /// </summary>
        public static string Subscriptions_Date_August5 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.August5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 sierpnia.
        /// </summary>
        public static string Subscriptions_Date_August8 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.August8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 lipca.
        /// </summary>
        public static string Subscriptions_Date_July18 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.July18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 lipca.
        /// </summary>
        public static string Subscriptions_Date_July21 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.July21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 lipca.
        /// </summary>
        public static string Subscriptions_Date_July24 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.July24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28 lipca.
        /// </summary>
        public static string Subscriptions_Date_July28 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.July28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 września.
        /// </summary>
        public static string Subscriptions_Date_September12 {
            get {
                return ResourceManager.GetString("Subscriptions.Date.September12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień wyszukiwaną frazę lub wybierz inną kategorię..
        /// </summary>
        public static string Subscriptions_Empty_Description {
            get {
                return ResourceManager.GetString("Subscriptions.Empty.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak pasujących subskrypcji.
        /// </summary>
        public static string Subscriptions_Empty_Title {
            get {
                return ResourceManager.GetString("Subscriptions.Empty.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string Subscriptions_Filter_AI {
            get {
                return ResourceManager.GetString("Subscriptions.Filter.AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        public static string Subscriptions_Filter_All {
            get {
                return ResourceManager.GetString("Subscriptions.Filter.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edukacja.
        /// </summary>
        public static string Subscriptions_Filter_Education {
            get {
                return ResourceManager.GetString("Subscriptions.Filter.Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprogramowanie.
        /// </summary>
        public static string Subscriptions_Filter_Software {
            get {
                return ResourceManager.GetString("Subscriptions.Filter.Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        public static string Subscriptions_Filter_Streaming {
            get {
                return ResourceManager.GetString("Subscriptions.Filter.Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie subskrypcje, koszty i terminy płatności w jednym miejscu. Zobacz, ile naprawdę kosztują Cię usługi cyfrowe..
        /// </summary>
        public static string Subscriptions_Header_Description {
            get {
                return ResourceManager.GetString("Subscriptions.Header.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrola cyklicznych wydatków.
        /// </summary>
        public static string Subscriptions_Header_Eyebrow {
            get {
                return ResourceManager.GetString("Subscriptions.Header.Eyebrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywne usługi i najbliższe płatności.
        /// </summary>
        public static string Subscriptions_List_Description {
            get {
                return ResourceManager.GetString("Subscriptions.List.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następna płatność.
        /// </summary>
        public static string Subscriptions_List_NextPayment {
            get {
                return ResourceManager.GetString("Subscriptions.List.NextPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje subskrypcje.
        /// </summary>
        public static string Subscriptions_List_Title {
            get {
                return ResourceManager.GetString("Subscriptions.List.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywne subskrypcje.
        /// </summary>
        public static string Subscriptions_Metrics_Active {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 więcej niż w zeszłym roku.
        /// </summary>
        public static string Subscriptions_Metrics_ActiveHint {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.ActiveHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt miesięczny.
        /// </summary>
        public static string Subscriptions_Metrics_Monthly {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnio 57,24 zł za usługę.
        /// </summary>
        public static string Subscriptions_Metrics_MonthlyHint {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.MonthlyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możliwe oszczędności.
        /// </summary>
        public static string Subscriptions_Metrics_Savings {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szacunkowo w skali roku.
        /// </summary>
        public static string Subscriptions_Metrics_SavingsHint {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.SavingsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt roczny.
        /// </summary>
        public static string Subscriptions_Metrics_Yearly {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prognoza dla aktywnych usług.
        /// </summary>
        public static string Subscriptions_Metrics_YearlyHint {
            get {
                return ResourceManager.GetString("Subscriptions.Metrics.YearlyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj subskrypcji....
        /// </summary>
        public static string Subscriptions_Search_Placeholder {
            get {
                return ResourceManager.GetString("Subscriptions.Search.Placeholder", resourceCulture);
            }
        }
    }
}
